### ISSUE TITLE
Error whilst cabal installing: `[]' of kind `* -> *' is not fully applied

### ISSUE THREAD

**Issue by Duta** [reinerp/first-class-patterns#3]
When running `cabal install first-class-patterns-0.3.2.1`, I get the error:

    Data\Pattern\Base\Difference.hs:36:44:
        `[]' of kind `* -> *' is not fully applied
        In the kind `[] -> *'
        In an expression type signature: forall (t :: [] -> *). D t []
        In the expression:
            ghc-prim:GHC.Prim.coerce (zeroD :: CoerceD t []) ::
              forall (t :: [] -> *). D t []

I also get this with first-class-patterns-{0.3.2,0.3.1,0.3.0}. With 0.2.0 I get dependency issues, and with 0.1.0 I get `The INLINE pragma for default method 'f' lacks an accompanying binding` (where f is in {closure, assoc, rightIdent}).

I'd love to install and use this, but I can't :( Is this a known issue? (/how do I get past it?)

**Comment by byorgey** [comment]
What version of GHC are you using?  I'm guessing 7.10?

**Comment by Duta** [comment]
7.8.3. Might that be the problem?

**Comment by byorgey** [comment]
Hmm, I would expect it to work on 7.8.3.  I will try to look into it, though I may not be able to get to it for a while.  I am not really using `first-class-patterns` any more.

**Comment by Duta** [comment]
That's fair enough. I though I'd ask, at least. What're you using in preference? Regular patterns, or something else?

**Comment by byorgey** [comment]
Yes, I just do regular pattern matching.  The ideas embodied in this
library are super cool, and long ago I had some ideas of how I might use
it, which is why I took over maintaining it.  But in practice I find that I
don't really use it.  Though perhaps if I thought harder I could find
places where it would be useful, and I haven't used it just because I am so
used to the alternative that I didn't really think of it.

**Comment by byorgey** [comment]
Uploaded to hackage as `0.3.2.2`.  It builds for me, let me know how it works.

**Comment by Duta** [comment]
Installed perfectly. Thanks!
