### ISSUE TITLE
Support build with 'stack'

### ISSUE THREAD

**Issue by ChShersh** [reinerp/first-class-patterns#5]
This will be a first step towards having `first-class-patterns` package on Stackage.

**Comment by byorgey** [comment]
Hi @ChShersh , great!  The easiest way is probably just to make your own fork.  When you next upload to Hackage you can edit the `.cabal` file to list yourself as the maintainer and  to point to your fork instead of this one.  If you let me know your Hackage username I will give you upload permissions.

**Comment by ChShersh** [comment]
@byorgey Great! Here is my Hackage username:

* http://hackage.haskell.org/user/shersh

**Comment by byorgey** [comment]
OK, you should be able to upload to Hackage now.  Have fun!
